.TH "Process.h" 3 "Mon May 23 2022" "Version 2022.05" "FCFS" \" -*- nroff -*-
.ad l
.nh
.SH NAME
Process.h
.SH SYNOPSIS
.br
.PP
\fC#include <ostream>\fP
.br
\fC#include <string>\fP
.br

.SS "Classes"

.in +1c
.ti -1c
.RI "class \fBProcess\fP"
.br
.RI "Class to emulate process proprieties\&. "
.in -1c
.SH "Author"
.PP 
Generated automatically by Doxygen for FCFS from the source code\&.
